# Generated by Django 4.1 on 2022-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "client_code",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                ("surname", models.CharField(blank=True, max_length=254, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("linked_clients", models.ManyToManyField(to="api.client")),
            ],
        ),
    ]
